version: "3.5"

services:
  px_server:
    container_name: px_server
    build:
      context: ./BUILD/
      args:
       - DB_LOGIN_A=px_user
       - DB_PASSWORD_A=px_pass
       - DB_NAME_A=px_base
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped